use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct Card {
    card_id: u64,
    foil_card_id: u64,
    card_set_id: u64,
    card_name: Option<String>,
    is_foil: u8,
    char_type: u8,
    clan: u8,
    tribe_name: String,
    skill: String,
    skill_condition: String,
    skill_target: String,
    skill_option: String,
    skill_preprocess: String,
    skill_disc: String,
    org_skill_disc: String,
    evo_skill_disc: String,
    org_evo_skill_disc: String,
    cost: u8,
    atk: u8,
    life: u8,
    evo_atk: u8,
    evo_life: u8,
    rarity: u8,
    get_red_ether: u32,
    use_red_ether: u32,
    description: String,
    evo_description: String,
    cv: String,
    copyright: Option<String>,
    base_card_id: u64,
    tokens: Option<String>,
    normal_card_id: u64,
    format_type: u8,
    restricted_count: u32,
}
