use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize)]
pub struct Card {
    card_id: u64,
    foil_card_id: u64,
    card_set_id: u64,
    card_name: Option<String>,
    is_foil: u8,
    char_type: u8,
    clan: u8,
    tribe_name: String,
    skill: String,
    skill_condition: String,
    skill_target: String,
    skill_option: String,
    skill_preprocess: String,
    skill_disc: String,
    org_skill_disc: String,
    evo_skill_disc: String,
    org_evo_skill_disc: String,
    cost: u8,
    atk: u8,
    life: u8,
    evo_atk: u8,
    evo_life: u8,
    rarity: u8,
    get_red_ether: u32,
    use_red_ether: u32,
    description: String,
    evo_description: String,
    cv: String,
    copyright: Option<String>,
    base_card_id: u64,
    tokens: Option<String>,
    normal_card_id: u64,
    format_type: u8,
    restricted_count: u32,
}

impl Default for Card {
    fn default() -> Card {
        Card {
            card_id: 1,
            foil_card_id: 2,
            card_set_id: 3,
            card_name: Some(String::from("カード名")),
            is_foil: 4,
            char_type: 5,
            clan: 6,
            tribe_name: String::from("tribe"),
            skill: String::from("スキル"),
            skill_condition: String::from("cond"),
            skill_target: String::from("target"),
            skill_option: String::from("opt"),
            skill_preprocess: String::from("prepro"),
            skill_disc: String::from("disc"),
            org_skill_disc: String::from("org_disc"),
            evo_skill_disc: String::from("evo_disc"),
            org_evo_skill_disc: String::from("org_evo_disc"),
            cost: 7,
            atk: 8,
            life: 9,
            evo_atk: 10,
            evo_life: 11,
            rarity: 12,
            get_red_ether: 13,
            use_red_ether: 14,
            description: String::from("カード説明"),
            evo_description: String::from("進化したカードの説明"),
            cv: String::from("声優"),
            copyright: None,
            base_card_id: 15,
            tokens: None,
            normal_card_id: 16,
            format_type: 17,
            restricted_count: 18,
        }
    }
}
